### ISSUE TITLE
Seems like doc build fails

### ISSUE THREAD

**Issue by RichoDemus** [RichoDemus/bevy-console#8]
https://docs.rs/crate/bevy_console/0.3.0/builds/517246

```
# rustc version
rustc 1.61.0-nightly (10cc7a6d0 2022-02-26)
# docs.rs version
docsrs 0.6.0 (3968c84 2022-02-20)

# build log
[INFO] running `Command { std: "docker" "create" "-v" "/home/cratesfyi/workspace/builds/bevy_console-0.3.0/target:/opt/rustwide/target:rw,Z" "-v" "/home/cratesfyi/workspace/builds/bevy_console-0.3.0/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/cratesfyi/workspace/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/cratesfyi/workspace/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "DOCS_RS=1" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--cpus" "3" "--user" "1001:1001" "--network" "none" "ghcr.io/rust-lang/crates-build-env/linux@sha256:0cd99ca24d8e8c98e67c542213511d985b8778b5bdcbb160e038429496686047" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "rustdoc" "--lib" "-Zrustdoc-map" "-Z" "unstable-options" "--config" "build.rustdocflags=[\"-Z\", \"unstable-options\", \"--emit=invocation-specific\", \"--resource-suffix\", \"-20220226-1.61.0-nightly-10cc7a6d0\", \"--static-root-path\", \"/\", \"--cap-lints\", \"warn\", \"--disable-per-crate-search\"]" "-Zunstable-options" "--config=doc.extern-map.registries.crates-io=\"https://docs.rs/{pkg_name}/{version}/x86_64-unknown-linux-gnu\"" "-j3" "--target" "x86_64-unknown-linux-gnu", kill_on_drop: false }`
[INFO] [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[INFO] [stdout] aca9076cdcf3dcea9b766591b4ead5b550d6edc4e29e3afeeaff5da784921503
[INFO] running `Command { std: "docker" "start" "-a" "aca9076cdcf3dcea9b766591b4ead5b550d6edc4e29e3afeeaff5da784921503", kill_on_drop: false }`
[INFO] [stderr]    Compiling anyhow v1.0.55
[INFO] [stderr]     Checking owned_ttf_parser v0.15.0
[INFO] [stderr]    Compiling xcb v0.8.2
[INFO] [stderr]     Checking regex v1.5.4
[INFO] [stderr]     Checking nom-supreme v0.6.0
[INFO] [stderr] error: failed to run custom build command for `xcb v0.8.2`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/xcb-efe71022a80f5e43/build-script-build` (exit status: 101)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   error occured in handler:  ('request: ', ('xcb', 'SELinux', 'GetClientContext'))
[INFO] [stderr]   Traceback (most recent call last):
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 2448, in <module>
[INFO] [stderr]       module.generate()
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/xcbgen/state.py", line 108, in generate
[INFO] [stderr]       self.close()
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 296, in rs_close
[INFO] [stderr]       _f.writeout(os.path.join(module.rs_srcdir, "ffi", "%s.rs" % _module_name(_ns.ext_name)))
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 114, in writeout
[INFO] [stderr]       with open(path, 'w') as f:
[INFO] [stderr]   OSError: [Errno 30] Read-only file system: '/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/src/ffi/selinux.rs'
[INFO] [stderr]   Error in sys.excepthook:
[INFO] [stderr]   Traceback (most recent call last):
[INFO] [stderr]     File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 119, in apport_excepthook
[INFO] [stderr]       pr.add_user_info()
[INFO] [stderr]     File "/usr/lib/python3/dist-packages/apport/report.py", line 426, in add_user_info
[INFO] [stderr]       user = pwd.getpwuid(os.geteuid())[0]
[INFO] [stderr]   KeyError: 'getpwuid(): uid not found: 1001'
[INFO] [stderr] 
[INFO] [stderr]   Original exception was:
[INFO] [stderr]   Traceback (most recent call last):
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 2448, in <module>
[INFO] [stderr]       module.generate()
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/xcbgen/state.py", line 108, in generate
[INFO] [stderr]       self.close()
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 296, in rs_close
[INFO] [stderr]       _f.writeout(os.path.join(module.rs_srcdir, "ffi", "%s.rs" % _module_name(_ns.ext_name)))
[INFO] [stderr]     File "/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/rs_client.py", line 114, in writeout
[INFO] [stderr]       with open(path, 'w') as f:
[INFO] [stderr]   OSError: [Errno 30] Read-only file system: '/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/src/ffi/selinux.rs'
[INFO] [stderr]   thread 'main' panicked at 'processing of /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/xml/xselinux.xml returned non-zero (1)', /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.2/build.rs:75:17
[INFO] [stderr]   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[INFO] [stderr] warning: build failed, waiting for other jobs to finish...
[INFO] [stderr] error: build failed
[INFO] running `Command { std: "docker" "inspect" "aca9076cdcf3dcea9b766591b4ead5b550d6edc4e29e3afeeaff5da784921503", kill_on_drop: false }`
[INFO] running `Command { std: "docker" "rm" "-f" "aca9076cdcf3dcea9b766591b4ead5b550d6edc4e29e3afeeaff5da784921503", kill_on_drop: false }`
[INFO] [stdout] aca9076cdcf3dcea9b766591b4ead5b550d6edc4e29e3afeeaff5da784921503

```

**Comment by makspll** [comment]
I believe this has been solved since the 0.4.0 build docs are available: https://docs.rs/bevy_console/latest/bevy_console/
